NEXTPL-435--Investigate-and-fix-security-issues-for-mstform
isprojects/mstform pull request #164
Opened 2021-12-22 15:05 UTC by jopispnext

Updated a lot of packages and tested the demo env.

Everything seems to work fine.

Not sure why all the extra whitespace is added in the CHANGES.md.

2021-12-23 07:59 UTC, Joris2Jansen approved these changes

2022-01-03 10:11 UTC, RickLucassen requested changes

2022-01-03 10:11 UTC, RickLucassen commented on package.json
> +    "version": "1.32.1",
Could you revert this? A release will be made when ready from master :)

2022-01-03 10:20 UTC, RickLucassen approved these changes

2022-01-03 10:21 UTC, merged