Non recursive loop when using flatAccessors
isprojects/mstform pull request #177
Opened 2024-09-12 11:22 UTC by arrahimi-ispnext

The recursive loop when executing flatAccessors can in some cases lead to maximum call stack error, to prevent this it has been transformed to a non recursive loop. Downside is that we use pop instead of shift causing the flatAccessor list not to be ordered chronologically.

2024-09-12 12:17 UTC, arrahimi-ispnext commented
Add tests

2024-09-13 13:19 UTC, kdleijer approved these changes

2024-09-16 10:30 UTC, randywanga requested changes
Please update the changelog to describe this change.

2024-09-16 14:16 UTC, randywanga approved these changes

2024-09-17 11:10 UTC, merged